config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  root 'users#new'
  resources :sessions
  resources :posts
  resources :users
  resources :favorites, only: [:create, :destroy, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  validates :image, presence: true
  validates :image_url, presence: true
  validates :content, presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_one :profile
    has_many :posts
    has_many :favorites, dependent: :destroy
    validates :fullname, presence: true, length: {maximum: 40}
    validates :email, presence: true, uniqueness: true, length: {maximum: 200},format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    before_validation { email.downcase! }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def current_user
        @current_user ||= User.find_by(id: session[:user_id])
      end
    def logged_in?
        current_user.present?
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def index
     @favorites=Favorite.all
    end
    def create
       favorite = current_user.favorites.create(post_id: params[:post_id])
       redirect_to posts_url, notice: "#{favorite.post.user.fullname}'s post has been liked"
    end
    def show
      @favorite = current_user.favorites.find_by(post_id: @post.id)
    end
    def destroy
       favorite = current_user.favorites.find_by(id: params[:id]).destroy
       redirect_to posts_url, notice: "#{favorite.post.user.fullname}'s post has been unliked"
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all
  end
  def show
  end
  def new
    @post = Post.new
  end
  def edit
  end
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
  def set_post
    @post = Post.find(params[:id])
  end
  def post_params
      params.require(:post).permit(:image, :content, :user_id)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  def index
    @profiles = Profile.all
  end
  def show
  end
  def new
    @profile = Profile.new
  end
  def edit
  end
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_profile
    @profile = Profile.find(params[:id])
  end
  def profile_params
    params.require(:profile).permit(:image, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to posts_path(user.id)
    else
      flash.now[:danger] = 'Login failed'
      render 'new'
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'You logged out'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all
  end
  def show
  end
  def new
    @user = User.new
  end
  def edit
  end
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to new_session_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:email, :phonenumber, :fullname, :username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
        @current_user ||= User.find_by(id: session[:user_id])
      end
    def logged_in?
        current_user.present?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<% @favorites.each do |favorite| %>
<center>
<div class="card text-center" style="width:900px;border-radius:30px;">
  <div class="card-body">
    <h5 class="card-title"><%= favorite.user.fullname %></h5>
    <%= image_tag favorite.post.image.url, class:"upload" %><br>
    <%= link_to 'Back', posts_path, class:"btn" %>
</div><br>
<% end %>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#"><%= image_tag("logo.png", class:"logo") %><selif style="height:400px;">|</selif>&nbsp;<selif style="font-family:cursive;font-size:20px;"><b>Instragram</b></selif></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav" style="margin-left:600px;">
          <li class="nav-item">
            <%= link_to "Profile", user_path(current_user.id), class:"nav-link", style:"color:black;" %>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", session_path(current_user.id), method: :delete, class:"nav-link", style:"color:black;" %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"><img src="https://img.icons8.com/android/24/000000/compass.png"></a>
          </li>
          <li class="nav-item">
            <%= link_to favorites_path do %>
              <%= image_tag "https://img.icons8.com/ios/50/000000/like.png", style:"width:30px;height:30px;margin-top:9px;" %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to profiles_path do %>
               <%= image_tag "https://img.icons8.com/material-outlined/50/000000/user.png", style:"width:30px;height:30px;margin-top:9.5px;" %>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
     <% end %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
    <div class="row" style="margin-left:400px;">
      <div class="col-md-6">
          <div class="form-group">
            <%= form.label :image %><br>
            <%= image_tag(@post.image.url, class:"imageupload" ) if @post.image && @post.image.url %>
            <%= form.file_field :image %>
            <%= form.hidden_field :image_cache %>
          </div>
          <div class="form-group">
            <%= form.label :content %>
            <%= form.text_area :content, class:"form-control", id:"exampleFormControlTextarea1", rows:'3' %>
          </div>
          <div class="form-group">
            <%= form.hidden_field :user_id, value: current_user.id %>
          </div>
          <%= form.submit class:"btn btn-primary" %>
          <%= link_to 'Back', posts_path, class:"btn" %>
        </form>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1 style="text-align: center;">Editing Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<%= link_to 'New Post', new_post_path, class:"btn btn-secondary btn-lg active" %>
  <% @posts.each do |post| %>
  <center>
<div class="card" style="width: 40rem;">
  <div class="card-body">
    <h5 class="card-title"><%= post.user.fullname %>s'Post</h5>
    <h5 class="card-title"><%= image_tag post.image.url, class:"upload" %></h5>
    <p class="card-text"><%= post.content %></p>
    <% if logged_in? %>
    <% if current_user.id == post.user_id%>
      <%= link_to 'Show', post, class:"btn btn-success" %>
      <%= link_to 'Edit', edit_post_path(post), class:"btn btn-primary" %>
      <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
    <% else %>
    <%= link_to 'Set A Favorite', post, class:"btn btn-info" %>
    <% end %>
    <% end %>
  </div>
</div>
</center>
<% end %>

app/views/posts/new.html.erb
<h1 style="text-align: center;">New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class="card text-center" style="width:900px;border-radius:30px;margin-left:150px;">
  <div class="card-header">
    <strong><%= @post.user.fullname %>s'Post</strong>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= image_tag @post.image.url, class:"upload" %></h5>
    <strong>Content</strong><p class="card-text"><%= @post.content %></p>
    <strong>User:</strong><p class="card-text"><%= @post.user.fullname %></p>
    <% if logged_in? %>
    <% if current_user.id == @post.user_id%>
    <%= link_to 'Comfirm Post', posts_path, data: { confirm: 'Are you sure do you want to Comfirm?' }, class:"btn btn-primary" %>
    <%= link_to 'Back', edit_post_path(@post), class:"btn" %>
    <% else %>
    <% unless @post.user_id == current_user.id %>
        <% if @favorite.present? %>
        <%= link_to 'Cancel Like', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
        <%= link_to 'Back', posts_path, class:"btn" %>
      <% else %>
        <%= link_to 'Like A Post', favorites_path(post_id: @post.id), method: :post, class: 'btn btn-primary' %>
        <%= link_to 'Back', posts_path, class:"btn" %>
    <% end %>
    <% end %>
    <% end %>
    <% end %>
  </div>
</div><br>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <center>
  <div class="field">
    <%= form.label :image %><br>
    <%= form.file_field :image %>
  </div><br>

  <div class="field">
    <% if logged_in? %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <% end %>
  </div>
  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
    <%= link_to 'Back', profiles_path, class:"btn btn" %>
  </div>
<% end %>
</center>

app/views/profiles/edit.html.erb
<h1 style="text-align: center;">Editing Profile</h1>

<%= render 'form', profile: @profile %>

app/views/profiles/index.html.erb
<div style="margin-left:250px;">
<% if logged_in? %>
<% check = 0, links='1', id=nil %>
<% @profiles.each do |profile| %>
<% if current_user.id == profile.user_id %>
  <% check = 1%>
  <%links = profile.image.url %>
  <%id =profile%>
<% end %>
<% end %>
<% if check==1 %>
<h4>profile picture</h4>
<%= image_tag links, class:"brand_logo" unless links.blank? %>
<strong class="user">
<%= link_to 'change Profile Picture', edit_profile_path(id), class:"btn btn-warning" %>
<%= link_to 'remove Profile Picture', id, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-info" %>
<%= link_to 'Posts', posts_path, class:"btn btn" %>
<% else %>
<%= image_tag "avatar.png", class:"brand_logo" %>
<%= link_to 'upload a profile picture', new_profile_path, class:"btn btn-secondary btn-lg active" %>
<%= link_to 'Posts', posts_path, class:"btn btn" %>
<% end %>
<% end %>
</strong>
</div>

app/views/profiles/new.html.erb
<h1 style="text-align: center;">New Profile</h1>

<%= render 'form', profile: @profile %>

app/views/profiles/show.html.erb
<div style="margin-left:250px;">
  <%= image_tag @profile.image.url, class:"brand_logo" %>
  <%= @profile.user.fullname %>
<%= link_to 'Confirm', profiles_path, class:"btn btn-warning" %>
<%= link_to 'Edit', edit_profile_path(@profile), class:"btn" %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <style>
      body{
        padding-top:4.2rem;
    padding-bottom:4.2rem;
    margin-top:20px;
        }
        a{
         text-decoration:none !important;
         }
         h1,h2,h3{
         font-family: 'Kaushan Script', cursive;
      }
  </style>
<body>
    <div class="container">
        <div class="row">
      <div class="col-md-5 mx-auto">
      <div id="first">
        <div class="myform form">
              <h3 style="text-align: center;">Create An Account</h3>
                           <div class="form-group">
                              <%= form.label :email %>
                              <%= form.text_field :email, class:"form-control", placeholder:"Enter email" %>
                           </div>
                           <div class="form-group">
                              <%= form.label :PhoneNumber %>
                              <%= form.text_field :phonenumber, class:"form-control", placeholder:"Enter Phone Number" %>
                           </div>
                           <div class="form-group">
                              <%= form.label :FullName %>
                              <%= form.text_field :fullname, class:"form-control", placeholder:"Enter Full Name" %>
                           </div>
                           <div class="form-group">
                              <%= form.label :UserName %>
                              <%= form.text_field :username, class:"form-control", placeholder:"Enter User Name" %>
                           </div>
                           <div class="form-group">
                              <%= form.label :password %>
                              <%= form.text_field :password, class:"form-control", placeholder:"Enter Password" %>
                           </div>
                           <div class="col-md-12 text-center ">
                              <%= form.submit class:"btn btn-block mybtn btn-primary tx-tfm" %>
                           </div>
                           <div class="form-group">
                              <p class="text-center">Already Have An Account <%= link_to "Login", new_session_path %><br/>
                           </div>
        </div>
      </div>
      </div>
    </div>
      </div>      
</body>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Phonenumber</th>
      <th>Fullname</th>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.phonenumber %></td>
        <td><%= user.fullname %></td>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @user.phonenumber %>
</p>

<p>
  <strong>Fullname:</strong>
  <%= @user.fullname %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>